image: node:17.3.0-alpine

before_script:
  - npm i -g firebase-tools

deploy-firestore:
  stage: deploy
  script:
    - firebase deploy --only firestore --token $FIREBASE_TOKEN
  only:
    refs:
      - master
    changes:
      - firebase-config/firestore.rules
      - firebase-config/firestore.indexes.json

deploy-functions:
  stage: deploy
  script:
    - cd functions
    - npm install
    - cd ..
    - firebase deploy --only functions --token $FIREBASE_TOKEN
  only:
    refs:
      - master
    changes:
      - functions/**/*

prod-hosting:
  stage: deploy
  script:
    - npm i
    - npm build
    - firebase deploy --only hosting --token $FIREBASE_TOKEN
  only:
    - master
  environment:
    name: production
